### PR TITLE
[backend] Chat System API #20

### LINKED ISSUE #20: [backend] Chat System API

### PR DESCRIPTION
**Pull request by ophinst**
Endpoint:

### 1. Get Chats `https://finit-api-ahawuso3sq-et.a.run.app/api/chat`
**_NEED TOKEN_**
Method: GET
Response:
```
{
    "message": "Chats retrieved successfully",
    "data": [
        {
            "chatId": "chat-zU6AcKvPxh",
            "members": [
                "fin-H8xduSgoh6",
                "fin-qrSuFWiz4x"
            ],
            "createdAt": "2024-03-18T03:46:38.600Z",
            "updatedAt": "2024-03-18T03:46:38.600Z"
        },
        {
            "chatId": "chat-DhbrzQweJ2",
            "members": [
                "fin-H8xduSgoh6",
                "fin-Iedhqmjfs5"
            ],
            "createdAt": "2024-03-18T03:47:09.938Z",
            "updatedAt": "2024-03-18T03:47:09.938Z"
        }
    ]
}
```

### 2. Get Chat by Id `https://finit-api-ahawuso3sq-et.a.run.app/api/chat/{receiverId}`
_**NEED TOKEN**_
Method: GET
Response:
```
{
    "message": "Chat retrieved successfully",
    "data": {
        "chatId": "chat-DhbrzQweJ2",
        "members": [
            "fin-H8xduSgoh6",
            "fin-Iedhqmjfs5"
        ],
        "createdAt": "2024-03-18T03:47:09.938Z",
        "updatedAt": "2024-03-18T03:47:09.938Z"
    }
}

### 3. Get Messages `https://finit-api-ahawuso3sq-et.a.run.app/api/message/{chatId}`
Method: GET
Response:
{
    "message": "Messages retrieved successfully",
    "data": [
        {
            "messageId": "chat-chat-zU6AcKvPxh-msg-dpJdEYZPxy",
            "chatId": "chat-zU6AcKvPxh",
            "senderId": "fin-H8xduSgoh6",
            "message": "pesen hati bang, hati gw hancur mulu",
            "createdAt": "2024-03-18T07:21:26.936Z",
            "updatedAt": "2024-03-18T07:21:26.936Z"
        },
        {
            "messageId": "chat-zU6AcKvPxh-msg-fcTTaW6yWW",
            "chatId": "chat-zU6AcKvPxh",
            "senderId": "fin-H8xduSgoh6",
            "message": "pesen hati bang, hati gw hancur mulu",
            "createdAt": "2024-03-18T07:22:24.816Z",
            "updatedAt": "2024-03-18T07:22:24.816Z"
        },
        {
            "messageId": "chat-zU6AcKvPxh-msg-TJjc-z74f2",
            "chatId": "chat-zU6AcKvPxh",
            "senderId": "fin-H8xduSgoh6",
            "message": "pesen hati bang, hati gw hancur mulu",
            "createdAt": "2024-03-18T07:36:00.408Z",
            "updatedAt": "2024-03-18T07:36:00.408Z"
        },
        {
            "messageId": "chat-zU6AcKvPxh-msg-qJdn8vM6x9",
            "chatId": "chat-zU6AcKvPxh",
            "senderId": "fin-H8xduSgoh6",
            "message": "pesen hati bang, hati gw hancur mulu",
            "createdAt": "2024-03-18T07:36:14.551Z",
            "updatedAt": "2024-03-18T07:36:14.551Z"
        },
        {
            "messageId": "chat-zU6AcKvPxh-msg-cVDjIzVanQ",
            "chatId": "chat-zU6AcKvPxh",
            "senderId": "fin-H8xduSgoh6",
            "message": "pesen hati bang, hati gw hancur mulu",
            "createdAt": "2024-03-18T07:36:15.615Z",
            "updatedAt": "2024-03-18T07:36:15.615Z"
        },
        {
            "messageId": "chat-zU6AcKvPxh-msg-zp_qKl8zHg",
            "chatId": "chat-zU6AcKvPxh",
            "senderId": "fin-H8xduSgoh6",
            "message": "pesen hati bang, hati gw hancur mulu",
            "createdAt": "2024-03-18T07:36:16.679Z",
            "updatedAt": "2024-03-18T07:36:16.679Z"
        },
        {
            "messageId": "chat-zU6AcKvPxh-msg-ncUw5mBFGt",
            "chatId": "chat-zU6AcKvPxh",
            "senderId": "fin-H8xduSgoh6",
            "message": "pesen hati bang, hati gw hancur mulu",
            "createdAt": "2024-03-18T07:36:17.802Z",
            "updatedAt": "2024-03-18T07:36:17.802Z"
        },
        {
            "messageId": "chat-zU6AcKvPxh-msg-iePORbWN3e",
            "chatId": "chat-zU6AcKvPxh",
            "senderId": "fin-H8xduSgoh6",
            "message": "pesen hati bang, hati gw hancur mulu",
            "createdAt": "2024-03-18T07:36:19.023Z",
            "updatedAt": "2024-03-18T07:36:19.023Z"
        },
        {
            "messageId": "chat-zU6AcKvPxh-msg-9qL5HFVdv1",
            "chatId": "chat-zU6AcKvPxh",
            "senderId": "fin-H8xduSgoh6",
            "message": "pesen hati bang, hati gw hancur mulu",
            "createdAt": "2024-03-18T07:36:20.318Z",
            "updatedAt": "2024-03-18T07:36:20.318Z"
        }
    ]
}
```

### 4. Send Message `https://finit-api-ahawuso3sq-et.a.run.app/api/message/{chatId}`
NEED TOKEN
Method: POST
Response:
```
{
    "message": "Message sent successfully",
    "data": {
        "messageId": "chat-zU6AcKvPxh-msg-V0d3fQtfjG",
        "message": "pesen hati bang, hati gw hancur mulu",
        "chatId": "chat-zU6AcKvPxh",
        "senderId": "fin-H8xduSgoh6",
        "updatedAt": "2024-03-18T07:36:25.051Z",
        "createdAt": "2024-03-18T07:36:25.051Z"
    }
}
```
Request Body:
```
{
    "message": "pesen hati bang, hati gw hancur mulu"
}
```

### CODE REVIEW

**Comment by ophinst** [comment]
for socket testing need ui from @fin-it/front-end-dev

**Review by zaydant — APPROVED** [review]
lgtm

**Review by Adam3131 — APPROVED** [review]
lgtm

**Review by kawakill76 — APPROVED** [review]
lgtm

**Pull request merged**
